### ISSUE TITLE
Abfragemöglichkeiten

### ISSUE THREAD

**Issue by realbadfox** [skainz92/wienernetze-smartmeter-php#1]
Gibt es eventuell noch weitere Anfrage Möglichkeiten?
Wie bekommt man 

.) Gesamtzählerstände
.) Hoch- und Niedertarif
.) usw.

Eine Beschreibung wäre gut, was tut welcher Paramter genau? 
wieso gibt man eine period an wenn man ein Anfangs- und Enddatum angeben muss?

**Comment by skainz92** [comment]
Hallo, 

ich habe keinerlei Kontakte zu Wien Energie, deshalb kann ich nur Daten auslesen die deren eigene Website ausließt / anzeigt. Dort kann der Netzwerkverkehr mitgeschnitten, ausgelesen und nachgebaut werden. 

- Der Gesamtzählerstand, ist bei mir ersichtlich auf der "Übersicht"-Seite. Die Daten auf dieser Seite werden mit der "welcome" Funktion ausgelesen.
- Zu Hoch-, und Niedertarif: Wie gesagt muss es eine Seite auf der offiziellen Wien Energy Smartmeter GUI geben. 
Ich hätte noch keine solche Seite gefunden. Haben Sie vielleicht einen Link?
- Sie meinen die Request-Parameter der einzelnen Funktionen? 
- Sie meinen die getConsumption() richtig? Ja, das stimmt wohl - deren API braucht als Req. Parameter immer dateFrom und dateTo. Das einzige das ich hier machen kann ist, wie bei createEvent() - den End-Parameter optional zu machen.

**Comment by realbadfox** [comment]
Gesamtzähler und Hoch- Niedertarif gibt es über diese Abfrage:
Jedoch weiß ich nicht wie die Homepage hier auf die Einspeisung umschaltet. Man kann nämlich auf der Homepage zwischen Einspeisung und Verbrauch umschalten, keine Ahnung wie man dies über einen Request machen kann.
Request:
https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2C/1.0/zaehlpunkt/meterReadings
Response:
{"meterReadings":[
{"value":311249,"type":"1-2:1.8.0","validated":true,"date":"2022-11-24T23:00:00.000Z"},
{"value":94353,"type":"1-2:1.8.1","validated":true,"date":"2022-11-24T23:00:00.000Z"},
{"value":216896,"type":"1-2:1.8.2","validated":true,"date":"2022-11-24T23:00:00.000Z"}]}

habe jetzt deine Parameter und Anfragen etwas umgebaut, jetzt kann man mehrere Zählpunkte auch abfragen (Verbrauch und Einspeisung).

**Comment by skainz92** [comment]
Gut, ich werde mir das bei Zeit mal ansehen. 

Es sollte eigentlich jetzt schon gehen mehrere Zählpunkte abzufragen. Dafür ist eigentlich der Parameter "meterpoint" gedacht. 
Was genau hat nicht funktioniert?

**Comment by realbadfox** [comment]
jaja mehrere Zählpunkte funktioniert schon, aber eben nicht diese Auflistung von oberhalb. Also die den Gesamtzählerstand ausgibt. sowohl für Einspeisung als auch für Verbrauch.
