### ISSUE TITLE
Login WN Server Error

### ISSUE THREAD

**Issue by mhaefele86** [skainz92/wienernetze-smartmeter-php#2]
Guten Abend,

ich bekomme am Ende der wn Funktion leider kein JSON, weil es einen Server Error gibt (die letzten beiden Variablen habe ich hier einmal auszugsweuse ausgegeben)

header:
`HTTP/1.1 500 Internal Server Error`

body:
```
<h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.NullPointerException
	java.net.URI$Parser.parse(URI.java:3042)
	java.net.URI.&lt;init&gt;(URI.java:588)
	java.net.URI.create(URI.java:850)
```

Mache ich ggf. etwas falsch oder hat Wiener Netze etwas umgestellt dass das Skript so aktuell nicht mehr funktioniert?

Danke!

**Comment by mhaefele86** [comment]
der original php output ist übrigens:

```
PHP Warning:  Attempt to read property "registration" on null in /home/markus/Schreibtisch/index.php on line 11
PHP Warning:  Attempt to read property "zaehlpunkt" on null in /home/markus/Schreibtisch/index.php on line 11
stdClass Object
(
    [Exception] => PROD API Gateway encountered an error. Error Message: Resource /messdaten/zaehlpunkt/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - null, Invocation Time:8:16:48 PM, Date:Apr 10, 2023,  Client IP - 46.125.69.90, User - Default and Application:null
)
```

**Comment by skainz92** [comment]
Hallo, 

Könnten Sie mir den Funktionsaufruf noch zeigen? 
Meine eigene App funktioniert noch.

**Comment by skainz92** [comment]
Falsch, meine eigene API funktioniert auch nicht mehr. 
Sie hat aber am 08.04.2023 noch funktioniert.

Es muss an der API seitens Wiener Netze eine Änderung gegeben haben. 
Die Wiener Netze GUI funktioniert noch, deshalb schließe ich ein temporäres Problem aus.

**Comment by skainz92** [comment]
Die URL hat sich geändert. 
Die nötigen Änderungen sind eingebaut und getestet. 

Vielen Dank fürs reporten!

**Comment by realbadfox** [comment]
Hallo stefan,

Könntest du mir die URL mitteilen?



MfG Christoph Püler



-------- Ursprüngliche Nachricht --------
Von: Stefan Kainz ***@***.***>
Datum: 11.04.23 00:06 (GMT+01:00)
An: skainz92/wienernetze-smartmeter-php ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [skainz92/wienernetze-smartmeter-php] Login WN Server Error (Issue #2)


Die URL hat sich geändert.
Die nötigen Änderungen sind eingebaut und getestet.

Vielen Dank fürs reporten!

**Comment by mhaefele86** [comment]
Guten Morgen,

leider klappt es nach dem Update (vielen Dank für die prompte Reaktion!!) noch immer nicht, hatte jetzt aber noch keine Zeit zu debuggen.

`php -f index.php `

```
PHP Fatal error:  Uncaught Error: Attempt to assign property "zaehlpunkt" on null in /home/markus/Schreibtisch/smartmeter-vienna.class.php:222
Stack trace:
#0 /home/markus/Schreibtisch/index.php(6): ViennaSmartmeter->getProfile()
#1 {main}
  thrown in /home/markus/Schreibtisch/smartmeter-vienna.class.php on line 222

```

**Comment by skainz92** [comment]
@realbadfox 
Die neue URL ist die https://service.wienernetze.at/sm/api/. 
Es haben sich aber auch noch andere Dinge geändert. Z.b. die dazugehörigen endpoints.
Es wäre also besser das file nochmal neu runterzuladen.

**Comment by skainz92** [comment]
@mhaefele86 

Hey, sollte mit letztem Update behoben sein. 
Bei mir hat php komischerweise keinen Fatal Error ausgespuckt wenn ich einem null object etwas zuweisen wollte ...
