### ISSUE TITLE
2. meterpoint / zaehlpunkt wird nicht angeführt

### ISSUE THREAD

**Issue by mhaefele86** [skainz92/wienernetze-smartmeter-php#4]
Bei mir wird leider nur ein Zählpunkt erkannt und ich sehe somit nur die Werte für den Verbrauch aber nicht die Werte der Einspeisung.

```
getProfile();

stdClass Object
(
    [id] => 55###
    [salutation] => Herr
    [lastname] => H****
    [firstname] => M****
    [email] => w****@h***.n***
    [defaultGeschaeftspartnerRegistration] => stdClass Object
        (
            [id] => 32###
            [registrationKey] => 81540#######
            [zaehlpunkt] => AT001000000000000000100000#######
            [status] => CONFIRMED
            [geschaeftspartner] => 120#######
            [completedAt] => 2022-06-28T18:25:22.098Z
        )

    [isZpsDonee] => 
    [registration] => stdClass Object
        (
            [zaehlpunkt] => AT001000000000000000100000#######
        )
)
```
```
welcome();

stdClass Object
(
    [meterReadings] => Array
        (
            [0] => stdClass Object
                (
                    [value] => 3210550
                    [type] => 1-2:1.8.0
                    [validated] => 1
                    [date] => 2023-04-10T22:00:00.000Z
                )
        )
)

```

**Comment by mhaefele86** [comment]
vielleicht kann @realbadfox auch noch teilen was er bei https://github.com/skainz92/wienernetze-smartmeter-php/issues/1#issuecomment-1330153364 umgebaut hatte ?

**Comment by skainz92** [comment]
Ahh ... verstehe.
Ich habe leider keine Einspeisung, deshalb kann ich die Aufrufe in der WE GUI vielleicht nicht sehen. 

Wenn mir jemand die Requests schickt, die über die GUI abgesetzt werden, kann ich die einbauen. 

lg

**Comment by mhaefele86** [comment]
> Wenn mir jemand die Requests schickt, die über die GUI abgesetzt werden, kann ich die einbauen.

Ich bin mir nicht sicher welche wirklich benötigt werden, weil man es an mehreren Stellen unterschiedlich umstellen würde.
Vielleicht können wir uns ein Screen-Sharing ausmachen um gemeinsam eine Lösung zu erarbeiten?
Terminfindung gerne per Mail: github.com@haefele.name

**Comment by realbadfox** [comment]
> vielleicht kann @realbadfox auch noch teilen was er bei [#1 (comment)](https://github.com/skainz92/wienernetze-smartmeter-php/issues/1#issuecomment-1330153364) umgebaut hatte ?

also ich verwende es inzwischen anders, und mache mittels curl usw. zuerst einen Login und dann die Abfrage, habe sie mir selbst konfiguriert für Tag/Monat/Jahr

falls das benötigt wird, kann ich diese gerne zur Verfügung stellen?

**Comment by schulti** [comment]
> also ich verwende es inzwischen anders, und mache mittels curl usw. zuerst einen Login und dann die Abfrage, habe sie mir selbst konfiguriert für Tag/Monat/Jahr
> 
> falls das benötigt wird, kann ich diese gerne zur Verfügung stellen?

Mich würde es interessieren! Vielen Dank!

**Comment by skainz92** [comment]
Die Zählpunkte können jetzt mittels getMeterPoints() ausgelesen werden. 
Hier werden auch die Einspeisungs-zählpunkte zurückgegeben. 

Die Werte können dann wieder mit getConsumption() ausgelesen werden.

Danke an @mhaefele86 fürs testen.
