### ISSUE TITLE
Api-Change?

### ISSUE THREAD

**Issue by kainers1** [skainz92/wienernetze-smartmeter-php#8]
Bin nicht ganz sicher, aber WN scheint die API geändert zu haben.

Bisher:
https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2B/1.0/zaehlpunkte/messwerte?zaehlpunkt=AT000000000000&datumVon=2023-11-21&datumBis=2023-11-22&wertetyp=QUARTER_HOUR

Neu:
https://api.wstw.at/gateway/WN_SMART_METER_PORTAL_API_B2B/1.0/zaehlpunkte/1000000/AT000000000000/messwerte?datumVon=2023-11-21&datumBis=2023-11-22&wertetyp=QUARTER_HOUR

Nach dem ich Kundennummer und Zählpunkt testweise hardgecodet habe, klappte es wieder.
Weiters muss derzeit das von-bis datum mindestens zwei Tage sein. Von 2023-11-21 bis 2023-11-21 geht auch im Smartmeter-Portal nicht.

Edit: Und das Projekt bitte zu https://github.com/topics/wiener-netze hinzufügen 😀

**Comment by skainz92** [comment]
Hallo, 

Hab das grade nachgestellt - stimmt ... 
Die neue URL funktioniert. Vielen Dank!

Werde schauen dass ich das heute Abend ändere.
Ich werd auch nochmal alles durchklicken und mir die Aufrufe anschauen - vielleicht gibt es etwas neues das man verwenden kann.
die getConsumption geht auch nicht mehr ...

Ärgerlich, aber auch verständlich, weil die API auf deren Gui zugeschnitten ist...

Vielen Dank!

**Comment by kainers1** [comment]
habe mit dem autor der node-red implementierung geschrieben: kann auch sein, dass die gerade an der api herumbasteln und es später wieder geht. In der Api-Doku steht der alte Aufruf noch.

**Comment by skainz92** [comment]
Hmm ... 
Ich hab die getMeasurements jetzt mal so dass sie funktioniert ( mit der neuen URL ), und die getConsumption entfernt, weil die meiner Meinung nach ohnehin nicht mehr kompatibel ist mit dem wie sie vorher funktioniert hat. 

Zwecks dem Problem mit den mind. zwei Tagen - ich hab eine neue Funktion eingeführt "getConsumptionByDay" mehr oder weniger als Alternative zur getConsumption - die liefert zumindest die Daten für den angegebenen Tag, im 15min Interval. 

Ich werd die jetzt noch ein paar Mal testen und dann lad ichs hoch...

**Comment by skainz92** [comment]
Habs jetzt geupdatet und nochmal getestet - getMeasurements sollte jetzt wieder gehen.

**Comment by skainz92** [comment]
Könnten Sie das nochmal testen?

**Comment by schulti** [comment]
Hallo! Danke für das tolle Projekt und dass ihr den Code zur Verfügung stellt!

Bei mir funktioniert es jetzt auch wieder, aber er nimmt nur den `defaultGeschaeftspartnerRegistration->zaehlpunkt` (ich nutze aktuelle die `getConsumptionByDay`). Ich habe mehrere Smartmeter unter meinem Account registriert. Habt ihr vor, das noch anzupassen? Danke!

**Comment by skainz92** [comment]
Hey, 

stimmt, die getConsumptionByDay nimmt jetzt das ganze "profile"-object und nimmt automatisch diesen Zählpunkt. 
Ich werde das anpassen, sodass getConsumptionByDay wieder einen "zählpunkt"-string parameter nimmt. 

Ich werde versuchen das heute / morgen zu updaten.
danke fürs aufmerksam machen!

**Comment by skainz92** [comment]
done.
